modify logic of getting package folder path
kernel-mod/electron pull request #14
Opened 2022-04-06 00:28 UTC by Ruthenic

Dev Branch Edition:tm:  
  
don't merge until i fix the TODO

2022-04-06 00:41 UTC, Ruthenic commented
![image](https://user-images.githubusercontent.com/53356436/161873319-386caf04-a093-4610-a142-048ddab400c6.png)

2022-04-06 00:49 UTC, Ruthenic commented
just tested, and it works

2022-04-07 03:01 UTC, Kyza requested changes

2022-04-07 03:01 UTC, Kyza commented on src/core/packageLoader/getPackagesPath.ts
> +			const kernelPath = origPath
Missing semi-colon. Unacceptable.

2022-04-07 03:01 UTC, Kyza commented on src/core/packageLoader/getPackagesPath.ts
> +				fs.mkdirSync(packagesPath)
Disgrace.

2022-04-07 04:08 UTC, merged